# confirm
POST {{<reg_uri}}/confirmations
> Content-type: application/json
> Authorization: Basic {{<authorization}}
{
  "email": "{{<email}}",
  "token": "{{<token}}"
}
< 204

# create

POST {{<reg_uri}}/applications
> Content-type: application/json
> Authorization: Basic {{<authorization}}
{}
< 303
< Location: {{>app_uri}}

# Check

GET {{<app_uri}}
> Accept: application/json
> Authorization: Basic {{<authorization}}
< 200
< Content-type: application/json
{
  "id": "{{>app_id}}",
  "token": "{{>app_token}}"
}
